### ISSUE TITLE
start error?

### ISSUE THREAD

**Issue by henryzp** [mint-ui/docs#16]
报错信息如下：

```
> docs@0.0.0 dev /Users/zhangpu/Documents/frontEnd/mint-ui-docs
> npm run build:router && cooking watch -p


> docs@0.0.0 build:router /Users/zhangpu/Documents/frontEnd/mint-ui-docs
> node bin/build-router

router file done

[cooking@1.2.12] - Loaded success: saladcss
[cooking@1.2.12] - Loaded success: lint
[cooking@1.2.12] - Loaded success: vue

[cooking@1.2.12] - Loading server...
[cooking@1.2.12] - Listening at http://10.204.131.8:8075
Build completed in 17.827s


ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-21dec0e0&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-21dec0e0&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue 4:14-270 13:2-17:4 14:20-276
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-1ac83258&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/navbar.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-1ac83258&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/navbar.vue 4:14-282 13:2-17:4 14:20-288
 @ ./src/components/navbar.vue
 @ /Users/zhangpu/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-2f3a6756&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/phone.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-2f3a6756&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/phone.vue 4:14-281 13:2-17:4 14:20-287
 @ ./src/components/phone.vue
 @ /Users/zhangpu/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-markdown-loader/.cache/README-1.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-markdown-loader/.cache/README-1.vue 4:14-234 13:2-17:4 14:20-240
 @ ./~/vue-loader!./~/vue-markdown-loader/.cache/README-1.vue
 @ ./src/pages/README.md
 @ ./src/route.js
 @ ./src/main.js
 @ multi app
Child html-webpack-plugin for "index.html":

webpack: bundle is now VALID.
webpack: bundle is now INVALID.

Build completed in 1.285s


ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-21dec0e0&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-21dec0e0&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue 4:14-270 13:2-17:4 14:20-276
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-1ac83258&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/navbar.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-1ac83258&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/navbar.vue 4:14-282 13:2-17:4 14:20-288
 @ ./src/components/navbar.vue
 @ /Users/zhangpu/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-2f3a6756&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/phone.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-2f3a6756&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/phone.vue 4:14-281 13:2-17:4 14:20-287
 @ ./src/components/phone.vue
 @ /Users/zhangpu/~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/main.js
 @ multi app

ERROR in /usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-markdown-loader/.cache/README-1.vue
Module build failed: TypeError: plugins.slice is not a function
    at Object.module.exports (/Users/zhangpu/Documents/frontEnd/mint-ui-docs/node_modules/vue-loader/lib/style-rewriter.js:49:31)
 @ ./~/vue-style-loader!/usr/local/lib/~/cooking-cli/~/css-loader!./~/vue-loader/lib/style-rewriter.js!./~/vue-loader/lib/selector.js?type=style&index=0!./~/vue-markdown-loader/.cache/README-1.vue 4:14-234 13:2-17:4 14:20-240
 @ ./~/vue-loader!./~/vue-markdown-loader/.cache/README-1.vue
 @ ./src/pages/README.md
 @ ./src/route.js
 @ ./src/main.js
 @ multi app
```

node版本：v6.2.2

npm版本：3.10.6

cooking版本：1.2.12

另外问一下，成功之后访问什么地址？

**Comment by zhangxinxinWTB** [comment]
我也发现。。。报错如果没报错的话。
打开 http://10.242.6.130:8075/ 可以访问。

**Comment by necfol** [comment]
+1
node: v6.2.1
npm: 3.9.3
cooking: 1.5.0

**Comment by necfol** [comment]
@QingWei-Li 3q,fixed!
